Note:
COPY command to copy source code to Docker image is not necessary because:
python:2.7-onbuild will take care of it.


Confirmation:

$ docker build . -t guillierf/web

Sending build context to Docker daemon  6.144kB
Step 1/3 : FROM python:2.7-onbuild
# Executing 3 build triggers...
Step 1/1 : COPY requirements.txt /usr/src/app/
 ---> Using cache
Step 1/1 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Using cache
Step 1/1 : COPY . /usr/src/app
 ---> Using cache
 ---> b07befbc8928
Step 2/3 : EXPOSE 5000
 ---> Using cache
 ---> 038f1bd85fa4
Step 3/3 : CMD python app.py
 ---> Using cache
 ---> 54b79648ff9e
Successfully built 54b79648ff9e
Successfully tagged guillierf/web:latest
